### ISSUE TITLE
Some tutorials?

### ISSUE THREAD

**Issue by luzpaz** [JeromeL63/Wood-Frame#15]
Lets get some tutorials created so more people are exposed to how this workbench works + perhaps even some youtube? Perhaps @wayofwood ([website](https://wayofwood.com/)) may be interested in participating?

**Comment by JeromeL63** [comment]
Yes, you're right.
But I can't seem to free up time these months to advance the project! It will come back!

**Comment by JeromeL63** [comment]
hello,
I've made some videos, not beautiful but it's there(@luzpaz , @j-wiedemann ).
[add beam](https://youtu.be/la1BvfgFgLQ)
[add beam suite](https://youtu.be/IgMWci76Oj8)
[add panel ](https://youtu.be/_G4gYu-Vkkg)
[container mechanism](https://youtu.be/PF-BVeaTad0)
[attributes mechanism](https://youtu.be/g7brtsF-MAc)
[Listing concept](https://youtu.be/RZgyhkf-bjA)
[Strectch concept](https://youtu.be/6zNmxR6LGXA)

**Comment by JeromeL63** [comment]
PS: all new functions will be welcome to group wood working(ex: @wayofwoof)

**Comment by luzpaz** [comment]
Nice, I'l make a PR to add these to the README

**Comment by luzpaz** [comment]
Embedded some of the above clips to https://github.com/JeromeL63/Wood-Frame/pull/17
