### ISSUE TITLE
Potentially non-universal python modules

### ISSUE THREAD

**Issue by iantsmall** [JeromeL63/Wood-Frame#18]
I've just begun using Wood-Frame, and after installing it (in a fresh install of Freecad 0.19 on a Windows which I do not use for python development) I'm noticing several errors appearing in the console.

I believe this may be due to having not installed the python modules manually at some other point.

Errors below and a snapshot of the console: 

> No module named 'ezdxf'
>Error: Initializing one or more of the Draft modules failed, Draft will not work as expected.
>Cannot find icon: %windows_user_path%\AppData\Roaming\FreeCAD\Mod\Wood-Frame/Resources/icons/WFStretch.svg
>Unknown command 'WF_Export'
>Unknown command 'WF_Export'

![image](https://user-images.githubusercontent.com/4554003/77388288-0ec36680-6d66-11ea-8249-5ce825c76fc9.png)

**Comment by JeromeL63** [comment]
Hello,
yes you're right, an icon is missing(stretch).
Stretch is a concept, and need to be more developed... 
At this time, I'm unable to trigger the installation of ezdxf if the module is missing. That's the reason why Wf_export is not loaded.
to solve ezdxf issue, you can manually use pip to install it. In terminal :
pip install ezdxf
https://pip.pypa.io/en/stable/
