### ISSUE TITLE
positionning beams on diagonals rather than vertical or horizontal lines

### ISSUE THREAD

**Issue by juliencarnot** [JeromeL63/Wood-Frame#19]
First of all, thanks for this great workbench, it took me a lot of time to find it through the forum (the wiki only references an abandoned workbench) but it is really useful.

I'm working on a simple carpentry project, I could easily put together chevrons and pannes, and also semelles and montants (which I have cut with a plan to my roof shape), but I can't place my sablières, which are neither horizontal nor vertical. I tried clicking on the top ends of both montants which they should be on top of, and then tried to draw a line, but the beam is not placed like it should be (on the green line):
![image](https://user-images.githubusercontent.com/3848493/92292521-e1d2cc80-ef1d-11ea-8cd9-8ec076c77add.png)
Am I missing something? Thanks for your help understanding this workbench!

**Comment by JeromeL63** [comment]
Hello,
bravo for your modeling!
I'm sorry, but I don't have enough time to develop the workbench. I sincerely hope that someone will take over the project, I would very much like it to move forward too.

**Comment by juliencarnot** [comment]
Turns out setting the workplane right on the top of the montants and setting the snap to the workplane or parallel or perpendicular did the job. I'll try to add some references/documentation on the wiki, maybe through better visibility more contributors will help!
